name: Run Python Script Every 3 Hours

on:
  schedule:
    - cron: "0 */3 * * *"  # Führt den Workflow alle 3 Stunden aus

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4  # Aktualisierte Version

    - name: Set up Python
      uses: actions/setup-python@v4  # Aktualisierte Version
      with:
        python-version: '3.10'  # Verwende die gewünschte Python-Version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python trends.py  # Korrekte Skriptdatei angeben
